user_login:
    path:     /
    defaults: { _controller: AppBundle:Security:login }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check }

dashboard:
    path:    /dashboard
    defaults: { _controller: AppBundle:Dashboard:dashboard }

new_product:
    path:    /new/product
    defaults: { _controller: DocumentBundle:Product:newproduct }

new_document:
    path:    /new/document
    defaults: { _controller: DocumentBundle:Document:newdocument }

new_devis:
    path:    /new/devis
    defaults: { _controller: DocumentBundle:Document:newdevis }