user_login:
    path:     /
    defaults: { _controller: AppBundle:Security:login }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

user_login_check:
    path:    /user/login/check
    defaults: { _controller: AppBundle:Security:check }

dashboard:
    path:    /dashboard
    defaults: { _controller: AppBundle:Dashboard:dashboard }

new_product:
    path:    /new/product
    defaults: { _controller: DocumentBundle:Product:newproduct }

new_client:
    path:    /new/client
    defaults: { _controller: ClientBundle:Client:newclient }

liste_product:
    path:    /liste/product
    defaults: { _controller: DocumentBundle:Product:listeproduct }

liste_client:
    path:    /liste/client
    defaults: { _controller: ClientBundle:Client:listeclient }

edit_product:
    path:    /edit/product/{idproduct}
    defaults: { _controller: DocumentBundle:Product:editproduct }

edit_client:
    path:    /edit/client/{idclient}
    defaults: { _controller: ClientBundle:Client:editclient }

supr_product:
    path:    /supr/product/{idproduct}
    defaults: { _controller: DocumentBundle:Product:suprproduct }

supr_client:
    path:    /supr/client/{idclient}
    defaults: { _controller: ClientBundle:Client:suprclient }

new_document:
    path:    /new/document
    defaults: { _controller: DocumentBundle:Document:newdocument }

new_organisme:
    path:    /new/organisme
    defaults: { _controller: ClientBundle:Organisme:neworganisme }

liste_organisme:
    path:    /liste/organisme
    defaults: { _controller: ClientBundle:Organisme:listeorganisme }

edit_organisme:
    path:    /edit/organisme/{idorganisme}
    defaults: { _controller: ClientBundle:Organisme:editorganisme }

supr_organisme:
    path:    /supr/organisme/{idorganisme}
    defaults: { _controller: ClientBundle:Organisme:suprorganisme }

new_devis:
    path:    /new/devis
    defaults: { _controller: DocumentBundle:Document:newdevis }

new_ecole:
    path:    /new/ecole
    defaults: { _controller: ClientBundle:Ecole:newecole }

new_pdf:
    path:    /new/pdf
    defaults: { _controller: DocumentBundle:Document:pdf }

liste_ecole:
    path:    /liste/ecole
    defaults: { _controller: ClientBundle:Ecole:listeecole }

edit_ecole:
    path:    /edit/ecole/{idecole}
    defaults: { _controller: ClientBundle:Ecole:editproduct }

supr_ecole:
    path:    /supr/ecole/{idecole}
    defaults: { _controller: ClientBundle:Ecole:suprproduct }

stub:
    path:    /stub
    defaults: { _controller: ClientBundle:Stub:getStub}


